### ISSUE TITLE
Change markers images to more eye-candy ones.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [heldersepu/GMapCatcher#152]
```
What new or enhanced feature are you proposing?

Change markers images to more eye-candy ones. (see attachments)

What goal would this enhancement help you achieve?

New images won't block the underlying streets on the map too much and look
prettier.
```

Original issue reported on code.google.com by `mrdu...@gmail.com` on 9 Apr 2010 at 6:08

Attachments:
- [markers.zip](https://storage.googleapis.com/google-code-attachments/gmapcatcher/issue-152/comment-0/markers.zip)

**Comment by heldersepu** [comment]
Closing do to lack of input Pull Requests are welcome!
