### ISSUE TITLE
Better interface for bulk downloading

### ISSUE THREAD

**Issue by GoogleCodeExporter** [heldersepu/GMapCatcher#160]
```
An user (kongyuan) from bbs.meizu.com provides a great graphical interface
which can generate download.py's parameters to help users to download a
large area from google map. However it is an ActiveX program. See the
attachment picture.

I suggest us to support this function directly by GMapCatcher.


```

Original issue reported on code.google.com by `pi3or...@gmail.com` on 6 May 2010 at 3:41

Attachments:
- [area-selection.png](https://storage.googleapis.com/google-code-attachments/gmapcatcher/issue-160/comment-0/area-selection.png)

**Comment by heldersepu** [comment]
Closing do to lack of input Pull Requests are welcome!
