### ISSUE TITLE
add view distortion modes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [heldersepu/GMapCatcher#184]
```
What new or enhanced feature are you proposing?
one mode would be a 'fish eye' view from above, allowing the viewer to view a 
larger area, the limits at lower resolution than the center;
one mode could be similar to google earth's perspective view, that allows an 
'aircraft' style view

What goal would this enhancement help you achieve?
fun! :-)
quite practical too
```

Original issue reported on code.google.com by `Mark111...@gmail.com` on 20 Jul 2010 at 1:09

Attachments:
- [flying11.png](https://storage.googleapis.com/google-code-attachments/gmapcatcher/issue-184/comment-0/flying11.png)
- [flyingLA.png](https://storage.googleapis.com/google-code-attachments/gmapcatcher/issue-184/comment-0/flyingLA.png)

**Comment by heldersepu** [comment]
Closing do to lack of input Pull Requests are welcome!
