### ISSUE TITLE
Proxy connection

### ISSUE THREAD

**Issue by GoogleCodeExporter** [heldersepu/GMapCatcher#35]
```
Hi,

at first time, sorry by my very bad english.


I need configure configure proxy at my work to use "online" mode.


thanks.
```

Original issue reported on code.google.com by `bacteria...@gmail.com` on 23 Apr 2009 at 7:30

**Comment by heldersepu** [comment]
Not planning to support proxy any time soon ...
but Pull Requests are welcome
