### ISSUE TITLE
RMaps tile repo error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [heldersepu/GMapCatcher#432]
```
What steps will reproduce the problem?
 1.I have problem in dowlading map
 2. pls provide solution
 3. i have attch file below

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `g.santos...@gmail.com` on 24 Jun 2015 at 7:46

Attachments:
- [error](https://storage.googleapis.com/google-code-attachments/gmapcatcher/issue-432/comment-0/error)

**Comment by heldersepu** [comment]
RMaps repos not very used, closing this as wont fix
