### ISSUE TITLE
RMaps option downloads can mixup map sources within the same RMap sqlite file

### ISSUE THREAD

**Issue by Alfonico** [heldersepu/GMapCatcher#434]
Hello.

Windows XP, 7 and 10.
GMapCatcher 0.8.0.5
## ![rmaps_mixing_sources](https://cloud.githubusercontent.com/assets/18240623/14231393/c3d802d6-f981-11e5-8b33-e401ed1d16bb.jpg)

In this case, the RMaps SQlite file ends up with a mix of OpenCycle and VirtualEarth map tiles.
When trying to correct the issue by ticking the "update" option, nothing happens, the SQlite file is stuck with the mixed tiles.
Using the download doesn't correct anything.

I don't have this issue when using SQlite3 as the map option in "settings". If by mistake I change the map source, the SQlite file is not modified and accepts only the tiles from the original map source, no mistake seems possible.

Is it possible that the structures of the RMaps SQlite and the SQLite3 files share some similarities that could allow to correct the problem ?

Thanks and regards

**Comment by heldersepu** [comment]
The SQLite repos were not thoroughly tested, yes there could be many bugs...

https://github.com/heldersepu/gmapcatcher/blob/master/gmapcatcher/tilesRepo/tilesRepoSQLite3.py
https://github.com/heldersepu/gmapcatcher/blob/master/gmapcatcher/tilesRepo/tilesRepoOSM.py

**Comment by heldersepu** [comment]
Closing do to lack of input Pull Requests are welcome!
