### ISSUE TITLE
Geotiff export available ?

### ISSUE THREAD

**Issue by sladecraven** [heldersepu/GMapCatcher#436]
Is it possible to get a kind of geotiff export, for using with the gdal tools ?

**Comment by heldersepu** [comment]
Yes a **kind of geotiff** is exported with the map export.
The output of the export is two files a .PNG image and a .TXT file like the 
That TXT file is a [world file](http://resources.arcgis.com/en/help/main/10.2/index.html#//009t00000028000000) that contain info about the map

See Issue #420 for more details

**Comment by heldersepu** [comment]
![2016-04-06 09_27_05-gmapcatcher](https://cloud.githubusercontent.com/assets/545474/14318229/e3aeaa74-fbd9-11e5-911a-e7c10cdd5601.png)


![2016-04-06 09_27_50-gmapcatcher](https://cloud.githubusercontent.com/assets/545474/14318228/e3adeb70-fbd9-11e5-9a61-d76d81cb3741.png)

**Comment by heldersepu** [comment]
Closing do to lack of input Pull Requests are welcome!
