### ISSUE TITLE
Not generating exe files

### ISSUE THREAD

**Issue by rsantosveloso1** [heldersepu/gmapcatcher#437]
I am trying to compile this project (Version GMapCatcher-0.8.0.6) and generate an installer to windows OS.
I have used setup.bat file and installed all modules, however the *.exe (maps.exe, download.exe, ..) files are not generated.
The installer file is generated nicelly.

Am i missing any step?

**Comment by heldersepu** [comment]
You need to troubleshoot the steps in setup.bat, in line 35:
https://github.com/heldersepu/gmapcatcher/blob/master/installer/setup.bat#L35
`%SystemDrive%\PYTHON27\PYTHON.EXE setup.py py2exe`
we build the maps.exe on that line, after it executes (IF SUCCESSFUL) there should be some new folders and one of them will contain the *.exe files

Here is a version you can use to start your troubleshooting
https://github.com/heldersepu/gmapcatcher/blob/test/installer/setup.bat

**Comment by rsantosveloso1** [comment]
I did the test with the setup.bat file you mentioned before.

you can find a log file in appendix with the execution and a snapshot with my project directory tree.

I cannot find any exe files after the execution of the setup.

[log.txt](https://github.com/heldersepu/gmapcatcher/files/472197/log.txt)
![capturar](https://cloud.githubusercontent.com/assets/22193484/18515035/c7840606-7a8b-11e6-9bf6-18f6078c68cb.PNG)

Thanks in advance

Ricardo

**Comment by heldersepu** [comment]
Your image does not show the folder:
C:\Users\m23000\Documents\NetBeansProjects\MapCatcherNavy\MapCatcherNavy\src\dist
that should contain the exe files

And at the end of the log there is an error:
error: can't copy 'changelog': doesn't exist or not a regular file
you will have to troubleshoot that...

**Comment by rsantosveloso1** [comment]
There are no exe files in dist folder.

![capturar2](https://cloud.githubusercontent.com/assets/22193484/18542088/d2c7466e-7b20-11e6-95f8-cc608f337ada.PNG)

**Comment by rsantosveloso1** [comment]
Solved after changing  data_files  to 

 data_files = [ ('README',["README.md"]), ('changelog',["changelog.md"]) ]

  in setup.py



setup(
    name = NAME,
    description = 'Offline Map Viewer',
    version = VERSION,
    url = WEB_ADDRESS,
    console = ['download.py'],
    windows = [{
        'script': 'maps.py',
        'icon_resources': [(1, "images\maps.ico")],
    }],
    options = {
        'py2exe': {
            'packages':'encodings',
            'includes': 'cairo, pango, pangocairo, atk, gobject, gio',
            'dll_excludes': DLL_EXCLUDES,
        }
    },
    #data_files = ['changelog', 'README']
    data_files = [ ('README',["README.md"]), ('changelog',["changelog.md"]) ]
)

**Comment by heldersepu** [comment]
Thanks, Correction added to the setup:
https://github.com/heldersepu/gmapcatcher/commit/c4203b505f3da05211ceed6be3ffda29a8ac83fd
