### ISSUE TITLE
Google map offline feature

### ISSUE THREAD

**Issue by SanjitAtAditi** [heldersepu/gmapcatcher#439]
Hi,
We have integrated google map in our iOS app. We have the business version of it. Is there any way we can download the map tiles for offline use without opening the the map screen in iOS app. Please let us know.

**Comment by heldersepu** [comment]
Yes there is a way to download map tiles for offline use.

But you know more about YOUR iOS app than I do, I can tell you all about GMapCatcher, but I don't know anything about your app.

**Comment by SanjitAtAditi** [comment]
It'll be really helpful if you can tell me the way how to do it. I'll let you know in precise how our iOS app works. Basically we are just dropping a pin on a particular location on map. Right now if we load the map for a region in online and then if we turn off the data for the device map shows the tiles for already downloaded region. But our requirement is when we are launching the app for very first time we want to cache the tiles. And after that even if the data is turned off for the device we should be able to see the map tiles and we should be able to drop the pin.

**Comment by heldersepu** [comment]
Remember It's your App! I know nothing about your app...
I do not see any repositories on your GitHub profile.
Is your App OpenSource? 


If you want to know how I do it in GMapCatcher start reading the following:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServers/googleMaps.py
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServices.py

**Comment by SanjitAtAditi** [comment]
Sorry, my App is not OpenSource. Thanks for the link, I'll look into those.

**Comment by heldersepu** [comment]
What programming language is your app written in ?
GMapCatcher is written in Python

**Comment by SanjitAtAditi** [comment]
Yes, I saw your file extension. My app is written in Objective c.

**Comment by heldersepu** [comment]
Sorry... You wont be able to "Copy/Paste" the code.

You should know that Google does not like developer using the map tiles offline...
https://github.com/heldersepu/GMapCatcher/issues/210

If you have any more questions reach our directly via email: **heldersepu (at) gmail.com**

**Comment by SanjitAtAditi** [comment]
Ok. Anyway thanks a lot for your help. If anything is required will let you know via email.
