### ISSUE TITLE
How to specify directory scheme when using download script?

### ISSUE THREAD

**Issue by samehraban** [heldersepu/GMapCatcher#440]
I'm looking for a way to download satellite tiles in osm format. Is there any way to use download script and specify directory scheme or maybe convert the downloaded tiles to osm structure?

**Comment by heldersepu** [comment]
Yes you can do it. Yo have a few options:
- Change the code, set default to your favourite options: https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapConf.py#L127
-  Open GMapCatcher and change the Settings (those settigns also apply to the download script): 
https://github.com/heldersepu/GMapCatcher/blob/wiki/User_Guide.md#settings
- Manually change the config file, it should be located on folder: _%UserProfile%\.GMapCatcher_
