### ISSUE TITLE
Coredump in exit

### ISSUE THREAD

**Issue by citrin** [heldersepu/GMapCatcher#442]
mapcatcher dumps core file on exit at least on FreeBSD:
`pid 76858 (python2.7), uid 1072: exited on signal 3 (core dumped)`
but same behavior should be on other Unix like OSes if core dumps are enabled.

Dumping core is default action for SIGQUIT (and purpose of this signal):
https://en.wikipedia.org/wiki/Unix_signal#SIGQUIT
https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#index-SIGQUIT

There is comment in the script about system resources - can you elaborate?
On process exit all system resources held by process (files, sockets, e.t.c) are freed by OS anyway.

Suggested patch:
```
--- a/maps.py
+++ b/maps.py
@@ -8,7 +8,6 @@ import os
 import re
 import sys
 import time
-import signal
 import gobject
 import gmapcatcher.mapGPS as mapGPS
 import gmapcatcher.mapUtils as mapUtils
@@ -1335,9 +1334,4 @@ if __name__ == "__main__":
             continue
 
     main(conf_path)
-    pid = os.getpid()
-    # send ourselves sigquit, particularly necessary in posix as
-    # download threads may be holding system resources - python
-    # signals in windows implemented in python 2.7
-    if os.name == 'posix':
-        os.kill(pid, signal.SIGQUIT)
+    sys.exit(0)
```

**Comment by heldersepu** [comment]
I was not sure when or who added that os.kill ...

It was added by @MarkieMark a while back:
https://github.com/heldersepu/GMapCatcher/commit/4e801df99546a0a4b1b180fd6ba716154ca27f03#diff-35e38474d179833b9f7aebf1c987469fL871
And since I do not use "Unix like OSes" often I guess it never bother me...

**Comment by heldersepu** [comment]
And we welcome Pull request, that is easier than a pasted patch

**Comment by citrin** [comment]
Ok, I'll make pull request.
