### ISSUE TITLE
Tiles not downloading

### ISSUE THREAD

**Issue by PauW2804** [heldersepu/GMapCatcher#447]
Hi, recently opened GMapCatcher and its not working.
no maps are available.
I'm using leaflet and the OpenStreetmap locations are still working.
Is there a way I can change the path URL's in GMapCatcher?

Kind Regards
Paul

**Comment by heldersepu** [comment]
It could be that the default map([MAP_SERVERS[NOKIA]](https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapConf.py#L168)) has change [their map pattern](https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServers/nokia.py#L10)

Unfortunately the only way to change it at the moment is in code, here is a link to all the maps:
https://github.com/heldersepu/GMapCatcher/tree/master/gmapcatcher/mapServers
If yo know what needs to change send a Pull Reques

**Comment by heldersepu** [comment]
resolved on latest version
