### ISSUE TITLE
Provider DLL failed to initialize correctly

### ISSUE THREAD

**Issue by evidential** [heldersepu/GMapCatcher#449]
Hi, Im having problems installing v0.8.0.6, this is the error message received-

File "maps.py", line 25, in <module>
  File "gmapcatcher\mapUpdate.pyc", line 7, in <module>
  File "gmapcatcher\openanything.pyc", line 16, in <module>
  File "urllib2.pyc", line 94, in <module>
  File "httplib.pyc", line 80, in <module>
  File "mimetools.pyc", line 6, in <module>
  File "tempfile.pyc", line 35, in <module>
  File "random.pyc", line 885, in <module>
  File "random.pyc", line 97, in __init__
  File "random.pyc", line 113, in seed
WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly

**Comment by heldersepu** [comment]
What version of windows?

**Comment by evidential** [comment]
Hi Im using Win XP but via Parallels on a MacBook.



Seán Murphy
Evidential -
*Director/Consultant*
p: +44 (0)845 591 2333  m: +44 (0)7400 984 685
a: The Sharp Project, Thorp Road,
Manchester M40 5BJ
w: www.evidential.com  e: sean@evidential.com
<https://www.facebook.com/evidentialepe/>
<http://twitter.com/Evidential_EPE>
<https://www.linkedin.com/in/sean-murphy-2b774a1a/>

  Click here to find out more about Evidential's Expert Services
<https://evidential.com/expert-witness-service/>


   - CCTV ANALYSIS <https://evidential.com/portfolio/cctv/> & AUDIO
   ENHANCEMENT <https://evidential.com/portfolio/audio/>
   - COMPUTER EXAMINATION <https://evidential.com/portfolio/computer/> & MOBILE
   PHONE ANALYSIS <https://evidential.com/portfolio/mobile/>
   - FINGERPRINTS <https://evidential.com/portfolio/fingerprints/> & FORENSIC
   PHOTOGRAPHY <https://evidential.com/portfolio/photography/>
   - FIRE INVESTIGATIONS <https://evidential.com/portfolio/fire/> & FORENSIC
   SURVEYS <https://evidential.com/portfolio/survey/>
   - ELECTRONIC PRESENTATION OF EVIDENCE
   <https://evidential.com/electronic-presentation-of-evidence/> (EPE)

Information in this email is confidential and intended solely for
the recipient(s) and should not be disclosed to any other party. The
contents may not represent the views of Evidential Ltd. If you have
received this transmission in error, any disclosure, copying or
distribution is strictly prohibited. If you are not the
intended recipient please notify the sender immediately and delete this
email. Evidential is a limited company registered in England and
Wales. Registered
number: 08838036. Registered office: THE SHARP PROJECT, THORP ROAD,
MANCHESTER, M40 5BJ. Please consider the environment before printing this
email.

**Comment by heldersepu** [comment]
Sorry I no longer have any way of testing on Win XP...

**Comment by evidential** [comment]
Thanks anyway Helder.



Seán Murphy
Evidential -
*Director/Consultant*
p: +44 (0)845 591 2333  m: +44 (0)7400 984 685
a: The Sharp Project, Thorp Road,
Manchester M40 5BJ
w: www.evidential.com  e: sean@evidential.com
<https://www.facebook.com/evidentialepe/>
<http://twitter.com/Evidential_EPE>
<https://www.linkedin.com/in/sean-murphy-2b774a1a/>

  Click here to find out more about Evidential's Expert Services
<https://evidential.com/expert-witness-service/>


   - CCTV ANALYSIS <https://evidential.com/portfolio/cctv/> & AUDIO
   ENHANCEMENT <https://evidential.com/portfolio/audio/>
   - COMPUTER EXAMINATION <https://evidential.com/portfolio/computer/> & MOBILE
   PHONE ANALYSIS <https://evidential.com/portfolio/mobile/>
   - FINGERPRINTS <https://evidential.com/portfolio/fingerprints/> & FORENSIC
   PHOTOGRAPHY <https://evidential.com/portfolio/photography/>
   - FIRE INVESTIGATIONS <https://evidential.com/portfolio/fire/> & FORENSIC
   SURVEYS <https://evidential.com/portfolio/survey/>
   - ELECTRONIC PRESENTATION OF EVIDENCE
   <https://evidential.com/electronic-presentation-of-evidence/> (EPE)

Information in this email is confidential and intended solely for
the recipient(s) and should not be disclosed to any other party. The
contents may not represent the views of Evidential Ltd. If you have
received this transmission in error, any disclosure, copying or
distribution is strictly prohibited. If you are not the
intended recipient please notify the sender immediately and delete this
email. Evidential is a limited company registered in England and
Wales. Registered
number: 08838036. Registered office: THE SHARP PROJECT, THORP ROAD,
MANCHESTER, M40 5BJ. Please consider the environment before printing this
email.

**Comment by heldersepu** [comment]
Now that I remember, I did use VMWare with great success to test on multiple OS.
