### ISSUE TITLE
gmapcatcher.conf to Gmapcatcher folder

### ISSUE THREAD

**Issue by frotna** [heldersepu/GMapCatcher#450]
Hi.
Can you make that files in Users\Username\.GMapCatcher folder (gmapcatcher.conf/locations/markers) install them self within Gmapcatcher folder. This way app will become portable, ready to copy/paste it anywhere and ready for usage...

**Comment by heldersepu** [comment]
I experimented with that a while back and ran with issues on Linux ...
That was the only directory we can guarantee the user can write to.

But I guess if you want to code your own version you could start here:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapConst.py#L158

**Comment by frotna** [comment]
Hi.
I really don't know anything about coding, so can you please do it for me...
My targeted platform is windows...
Sincerely...

**Comment by heldersepu** [comment]
Reach me directly via email
