### ISSUE TITLE
Search Location not working.

### ISSUE THREAD

**Issue by zixuan75** [heldersepu/GMapCatcher#451]
I have tried a location exists but it is not working

**Comment by joelrorseth** [comment]
I also cannot get it working. Need a fix for a project I am working on.

**Comment by heldersepu** [comment]
Yes probably google (once again) changed the rules of the game.

If anyone is interested on troubleshooting this issue start here:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServers/googleMaps.py#L69

**Comment by heldersepu** [comment]
@joelrorseth if you are truly motivated to get this fixed contact me directly via email

**Comment by heldersepu** [comment]
Fixed on latest release
