### ISSUE TITLE
Map turn to north

### ISSUE THREAD

**Issue by aakash82** [heldersepu/GMapCatcher#452]
Hi,

i am a python newbie, can you please let know with your current project is there any option to keep map always to north (In GPS direction) while GPS is marking on map?

Like google map is doing while driving. The map is always be in driving direction while on GPS.

Regards,
Aakash

**Comment by heldersepu** [comment]
In the map north is always up.
This App is not Navigation App only an offline map viewer.

What you are asking will be quite complex! something I would not even consider at the moment

**Comment by aakash82** [comment]
Ok. What I am asking is to turn the map tiles to the GPS direction. Is that possible in any way?

**Comment by heldersepu** [comment]
> Is that possible in any way?

No such an option exists on GMapCatcher at the moment, you knew that right?

but if what you are asking is if it can be done, YES I have no doubt that it is possible to make the map rotate to true north reading from GPS, but like I mentioned I consider it to be quite complex and time consuming, I would not consider that without a financial incentive.

**Comment by aakash82** [comment]
Ok. Can you suggest some ways how to achieve this. Such that I can contribute it to your project.

**Comment by heldersepu** [comment]
You said:
>  i am a python newbie

I do not see you have any projects on GitHub, not even a fork of this project ...
What have you done with GMapCatcher?

**Comment by aakash82** [comment]
Yes. I have run the project and run is successful. I have not done anything yet with the project, but have an idea to do this as I have not seen in the code.

**Comment by heldersepu** [comment]
Please start by making a fork of the project, and get the source code using a Git client.
You mention you have an idea to do this... That's great! try it out and commit your changes to your fork, if you get stuck I will look into what you have done.

**Comment by aakash82** [comment]
Sure. Will do that.

**Comment by aakash82** [comment]
Hi,

I have been working on Windows 7 machine and I am getting an error regarding 'Microsoft Visual C++ Runtime Library' as 'This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.'

Do you have any idea why I am getting this?

**Comment by heldersepu** [comment]
Can you share some more details?
When are you getting that error?

**Comment by aakash82** [comment]
I am getting this error while running application with virtual GPS. While GPS feeds coming in.

**Comment by heldersepu** [comment]
what is a virtual GPS? I never used that before...
Is GMapCatcher working?

**Comment by heldersepu** [comment]
I do not see any code changes on your fork, so I'm going to close this issue.

**Comment by aakash82** [comment]
Virtual GPS will give us a GPS feeds without driving, Inhouse. And issue is coming so there are no changes in it,

**Comment by aakash82** [comment]
GMapCatcher is working.

**Comment by heldersepu** [comment]
sounds like the Virtual GPS is the one giving you the error? 
I do not have the source code for that...

Since this is not directly related to  GMapCatcher please contact me via email
