### ISSUE TITLE
Scale/zoom not working

### ISSUE THREAD

**Issue by TommyNesset** [heldersepu/GMapCatcher#453]
I've just downloaded GMapCatcher due to the need of a offline map.. But after download, the map only works in scale 15 and 16. In every other scale it's just "We are sorry, but we don't have maps at this zoom level for this region. Make sure our are online or try zooming out for a broader look"

I am online, and have tried multiple places but can't seem to get a better zoom.. I've also tried to batch download the area I want to zoom in.

**Comment by heldersepu** [comment]
What map service are you using ?
Have you tried with any other ?

**Comment by heldersepu** [comment]
Was doing some research and ...
The default map (Nokia) seems to have changed the format, they are denying access to the map tiles with the old format:
http://1.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/3/5/2/256/png8?app_id=SqE1xcSngCd3m4a1zEGb&token=r0sR1DzqDkS6sDnh902FWQ&lg=ENG

The new format has a different pattern:
http://1.base.maps.api.here.com/maptile/2.1/maptile/newest/normal.day/3/5/2/256/png8?app_id=bC4fb9WQfCCZfkxspD4z&app_code=K2Cpd_EKDzrZb1tz0zdpeQ&lg=eng

**Comment by heldersepu** [comment]
Issue resolved on latest version:
https://github.com/heldersepu/GMapCatcher/releases/tag/0.8.0.7
