### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by ale3andro** [heldersepu/GMapCatcher#455]
Hello,
first of all thank you for this great software. I am a teacher and I plan to use it at school (in offline mode because the internet connection speed is low).
Is there a feature for selection of other languages in downloaded maps?  Can I download maps for offline use in other language (other than English)? 
Thank you

**Comment by heldersepu** [comment]
No, not possible with the current implementation... But it will not be too hard to add something like that, if the map service has an option for that

What language(s) did you have in mind?
...and what map services do you use?

**Comment by ale3andro** [comment]
I want the Greek version of the maps.
RIght now I experiment with Nokia maps but ideally I would like to use Open Street Maps that I know that it has Greek city names.

**Comment by heldersepu** [comment]
I just tested and OSM does show city names in Greek:
![image](https://user-images.githubusercontent.com/545474/39961937-54548b4a-560f-11e8-98f0-857ef30d5812.png)

But if we go to Italy it shows in Italian:
![image](https://user-images.githubusercontent.com/545474/39961942-84651fde-560f-11e8-82ac-d8ed49620324.png)

What you are asking is to show the city names in Greek no matter the country?
I could not find any documentation about that in the OSM wiki, can you find anything about that?

**Comment by ale3andro** [comment]
I want Greek city names just for Greece.
In my OSM Map the city names are English (when the zoom>6) and mixed when the zoom is lower.
[here](https://ibb.co/mbGmmJ)
So I guess that this is an OSM issue not gmapcatcher.

**Comment by heldersepu** [comment]
I think that you might have a mix of old and new map tiles ...
Try to visit that section but with the [Force update] checked
