### ISSUE TITLE
Find Location of Tile

### ISSUE THREAD

**Issue by amthenia** [heldersepu/GMapCatcher#457]
Hi,
When I have a tile at /tiles/3/7/288/6
What is the location of that tile?

**Comment by heldersepu** [comment]
There is more than one location(lat,lon) in a tile...
A path like that seems to be from the  tilesRepoFS
Look into coord_to_path to see how it works:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/tilesRepo/tilesRepoFS.py#L123
