### ISSUE TITLE
add OpenTopoMap server

### ISSUE THREAD

**Issue by Gorsh2** [heldersepu/GMapCatcher#459]
Hi. First: thank you, your program is great!

I'm asking to add [OpenTopoMap](https://opentopomap.org/) server: a great resource when going outdoors, specially in areas without cell coverage.
The tiles are on a free license and there's no download limit (so far), as per [this link](https://opentopomap.org/about) (in german, but you can recognize the "CC-BY-SA" in there). 

The tileserver's link structure is the same as the other "open" style maps: 
 https://{a|b|c}.tile.opentopomap.org/{z}/{x}/{y}.png 
(In fact, in the meantime I've resorted to change every "cycle" for "topo" in OpenCycleMap.py :) )

Thanks again.

**Comment by Gorsh2** [comment]
Thanks... I now tried that: reverted OpenCycleMap.py, added OpenTopoMap.py as a different file, and added OTM in mapConst.py as suggested (in all three places where it seems to be needed: defined as 22, in MAP_SERVERS and MAP_SERVICES). 
Now the option appears, but both OCM and OTM are broken and I get the "We are sorry..." sign.

Any idea why?

**Comment by heldersepu** [comment]
It has been a while since I added a map service...
Look in the history of commits see if gives you any hints
