### ISSUE TITLE
How to download an area?

### ISSUE THREAD

**Issue by benderlidze** [heldersepu/GMapCatcher#462]
I set the center, width and height. But those width and height are ploted from center of the map or coordinates that I entered? And width and height are ploted from the top left corner or bottom left corner?
Thanks
![Screenshot_2](https://user-images.githubusercontent.com/8510813/67743986-f5bdc000-fa28-11e9-91fc-06f747513df9.png)

**Comment by heldersepu** [comment]
That should be an approximate representation of the screen you had  open at the time you launched the download window, I never consider anyone would require precise location when downloading map tiles...

I would recommend you to enable 'Location Status' set it to 'Mouse' you should see more details that way on the bottom of the screen
![Screenshot from 2019-10-29 18-48-06](https://user-images.githubusercontent.com/545474/67815335-0a2ba800-fa7d-11e9-93f7-0591abc55bdd.png)
