### ISSUE TITLE
No COPYING or LICENSE file in repo, which license is GMapCatcher under?

### ISSUE THREAD

**Issue by strypey** [heldersepu/GMapCatcher#464]
I can't see a COPYING or LICENSE file in the GMapCatcher repo. Which license is it under?

**Comment by heldersepu** [comment]
I never really cared much for LICENSE you can do whatever you want with the code

**Comment by strypey** [comment]
Understood, but in most countries your code is automatically placed under All Rights Reserved copyright as soon as you publish it. The very simplest license that that says "you can do whatever you want with the code" is the WTFPL:
https://directory.fsf.org/wiki/License:WTFPL-2

If you're put off by the obscenity, the Expact (or "MIT) license says the same thing, in more formal language:
https://directory.fsf.org/wiki/License:Expat

Let me know which you prefer, and I'll do a PR to add a COPYING file to your repo with the text of that license.

**Comment by heldersepu** [comment]
MIT sounds good to me

**Comment by heldersepu** [comment]
After I wrote that I started searching and we do have a LICENSE, just not a file:
https://github.com/heldersepu/GMapCatcher/blob/81bfbc4b9221f1f70a04f648920098245553879f/gmapcatcher/widgets/widCredits.py#L25

**Comment by strypey** [comment]
Cool. I've made a PR to add a LICENSE file, stating that the code is under GPLv2, and referencing that file for the list of authors:
https://github.com/heldersepu/GMapCatcher/pull/465

**Comment by heldersepu** [comment]
Merged

**Comment by heldersepu** [comment]
Do you actually use GMapCatcher?

**Comment by strypey** [comment]
@heldersepu
> Merged

Awesome!

> Do you actually use GMapCatcher?

Not yet, but now that I'm confident it's free code, I'll give it a test. I've added it to a table of [free code mapping apps](https://wiki.p2pfoundation.net/Free_Code_Map_Apps) I curate.
