### ISSUE TITLE
Image Size Preferences

### ISSUE THREAD

**Issue by robthomson** [heldersepu/GMapCatcher#466]
Hi

Fantastic feature for the software would be to enable a proxy folder with automatic image size modification.

Example situation as follows is when using this system:

https://github.com/yaapu/FrskyTelemetryScript

The end job requires using GMapCatcher.. then taking the files and converting them all to 100x100px.

It seems to me that it would be much better if this happens on the fly.  Would certainly be quicker to do at download time!

**Comment by heldersepu** [comment]
The current map tile size is not something we made up for GMapCatcher 256x256px is the golden standard, I have not come across any map provider that uses any other size.

My recommendation, reach out to those end users and have them follow proper standards ...

**Comment by heldersepu** [comment]
Here are few examples of map tiles from some of there providers we support

- https://maps-for-free.com/layer/relief/z0/row0/0_0-0.jpg
- http://a.tile.opencyclemap.org/cycle/0/0/0.png
- https://a.tile.openstreetmap.org/0/0/0.png

As you can see all are 256 squares

**Comment by robthomson** [comment]
Unfortunately the issue is more that the radio / hardware is not capable of using a large size.

**Comment by heldersepu** [comment]
You can try adding what you suggest, no one can stop you... 
But I do not see any value to GMapCatcher adding this feature
