### ISSUE TITLE
Zoom not working

### ISSUE THREAD

**Issue by LineF** [heldersepu/GMapCatcher#467]
Hi,

I have the same issue as in #453 described.
Sat and terrain only in level 15 and 16.
I'm using 0.8.0.9

Martin

**Comment by heldersepu** [comment]
What map service are you using ?
Have you tried with any other ?

**Comment by LineF** [comment]
Nokia was default. But I tried some others, too.
But there was no change at all: Always the same map style and sat and terrain only the error tiles...

I can save the map service under tab "change theme" and when I reopen the settings, the changed service is in the settings, but when I close and reopen the whole program, the default "nokia" reappears.
Is there a problem with installation?

Martin

**Comment by heldersepu** [comment]
Yes, there seem to be some permission issues...
The settings are saved on the folder: `%UserProfile%\.GMapCatcher` make sure that has proper access, you can try changing the permissions to allow full control to the everyone group

![permissions](https://user-images.githubusercontent.com/545474/80863572-613c5080-8c4b-11ea-86a6-17b8457db3d3.png)

**Comment by heldersepu** [comment]
You can also try the console downloader:
`download.exe --latitude=0 --longitude=10 --min-zoom=8`
 if successful you should see something like:
```
C:\Program Files (x86)\GMapCatcher>download.exe --latitude=0 --longitude=10 --min-zoom=8
Download somewhere (0.000000, 10.000000), range (0.050000, 0.050000), mapsource: " ", zoom level: 17 to 8

Downloading zl 17
Downloading zl 16
Downloading zl 15
Downloading zl 14
Downloading zl 13
Downloading zl 12
Downloading zl 11
Downloading zl 10
Downloading zl 9       ==*
Downloading zl 8       ==*
Download Complete!
. . . . .
```

**Comment by LineF** [comment]
In the meanwhile I can change the map sources.
I't not a access rights problem but a handling problem of the settings dialog:

When I open the "change theme", I go to the favourite map service and select one. Then I press "save". At that moment the settings window goes behind the main window and therefore is unvisible. Settings are not saved yet. Then I have to fetch the settings window back to the front via task bar. Then I have to press "save" again and can close the window. Now my settings are executed and the selected map service is active.

BTW:
I'm interested in Satellite tiles. Google has very current sat pics but it seems that google doesn't allow to download the pics by your tool.
On the other side the "virtual earth" allows to download sat pics but they are old and not so sharp.

Do you know a solution for that (at best downloading google tiles...)?

Thanks a lot for your great tool and your help!

Martin

**Comment by heldersepu** [comment]
from ... Zoom not working to a handling problem on settings
Yes the settings are buggy 

GMapCatcher no longer supports google, sorry.
for more details see: https://github.com/heldersepu/GMapCatcher/issues/210
