### ISSUE TITLE
Not downloading any satalite view map view is ok 

### ISSUE THREAD

**Issue by sparr88** [heldersepu/GMapCatcher#468]
not showing or downloading  satalite type maps when in online mode. Uninstalled and reinstalled. Tried all different providers Worked two weeks ago with Nokia, now will not show anything below zoom 12 help ?!

**Comment by heldersepu** [comment]
I just test Nokia satellite and got the same... regular maps still work...
My guess they changed the pattern for the satellite tiles, will try looking into

**Comment by heldersepu** [comment]
The tiles still correct and load fine on the browser:

- http://1.aerial.maps.api.here.com/maptile/2.1/maptile/newest/hybrid.day/6/37/16/256/png8?app_id=bC4fb9WQfCCZfkxspD4z&app_code=K2Cpd_EKDzrZb1tz0zdpeQ&lg=eng

- http://1.aerial.maps.api.here.com/maptile/2.1/maptile/newest/hybrid.day/0/0/0/256/png8?app_id=bC4fb9WQfCCZfkxspD4z&app_code=K2Cpd_EKDzrZb1tz0zdpeQ&lg=eng

they must be actively blocking GMapCatcher, you can try changing your agent name and web_address (you will need to manually edit `%UserProfile%/.GMapCatcher/gmapcatcher.conf`) but that would probably not last for long before they block again

**Comment by sparr88** [comment]
Change agent name and we address to what ?

**Comment by heldersepu** [comment]
> Change agent name and we address to what ?
to something else, make something up

**Comment by sparr88** [comment]
No luck for me. Just blank tiles :( can I capture and download them else
where ? Browser ?

**Comment by sparr88** [comment]
Suddenly it started to work again after. CHanging those .. weird
