### ISSUE TITLE
Unable to download satellite tiles from nokia maps

### ISSUE THREAD

**Issue by yaapu** [heldersepu/GMapCatcher#470]
Hi,
this is a recent thing, since a couple days sat tiles download from nokia maps has stopped.
I checked your suggestion to use the downloader.exe to test it properly and I get HTTP 404

```
C:\Program Files (x86)\GMapCatcher>download.exe --max-zoom=-2 --min-zoom=-2 --latitude=41.89017 --longitude=12.492265 --width=0.1 --height=0.1 --satellite
Download somewhere (41.890170, 12.492265), range (0.000899, 0.001208), mapsource: " ", zoom level: -2 to -2

Downloading zl -2       HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
 HTTP Error 404: Not Found
==*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*HTTP Error 404: Not Found
=*
Download Complete!
```
. . . . .

now the interesting part, I used fiddler to get the url receiving the 404, this is one of them

http://3.aerial.maps.api.here.com/maptile/2.1/maptile/newest/hybrid.day/19/280335/194838/256/png8?app_id=bC4fb9WQfCCZfkxspD4z&app_code=K2Cpd_EKDzrZb1tz0zdpeQ&lg=eng

if I do a get with the browser it works and shows the tile so the here map api has not changed, but when downloaded from gmapcacther I get an http 404

any ideas?

thanks a lot and congrats for your huge effort!

Alex

**Comment by heldersepu** [comment]
Yes they are actively blocking GMapCatcher
