### ISSUE TITLE
Question - Other tile download formats

### ISSUE THREAD

**Issue by evan0065** [heldersepu/GMapCatcher#471]
Hi, 

I am currently looking at the application and saw that the tilesets were downloaded as png images. Is there any way to change this option, such that it downloads as a vector tileset, like pbf files? 

Thanks!

**Comment by heldersepu** [comment]
Nope, no other format is available at the moment.

**Comment by evan0065** [comment]
Thanks! First of all, let me say that this app provides functionality to download that I _cannot find elsewhere._ Which is really great. 

On that note, I have a related question about how the files are downloaded. 

I was examining the file structure after exporting tiles, and saw that they didn't follow the usual `{z}/{x}/{y}.png` format. For example, one of my satellite downloads would have followed the '{z}/0/{x}/0/{y}.png` format, which isn't that big of a deal. But my other download, a regular street map, does not follow that format. 

If I open the `tiles` directory, I see the folders for each zoom level. Then, a number that starts at 16 and is halved for every directory. Then a bunch of folders, and inside, two folders that I don't understand, and within these folders, the tiles. Below is a very rudimentary depiction of the directory (I'm sorry that it looks terrible).

```
-> 2
----> 16
--------> 185
-------------> 10
----------------> tiles
-------------> 11
----------------> tiles
--------> ...
--------> 243
--- ...

-> 3
----> 8
------> ...
-> ..
-> 8
----> ...
```

More or less, my question is, how are the png tiles arranged upon download? I'm trying to export them and use them and cannot figure out a logical order. I would really appreciate any feedback. 

Thank you!

**Comment by heldersepu** [comment]
You can change that take a look at the user guide:
https://github.com/heldersepu/GMapCatcher/blob/wiki/User_Guide.md#main
It's the dropdown under the custom directory
