### ISSUE TITLE
Issue with zoom levels on tile export

### ISSUE THREAD

**Issue by evan0065** [heldersepu/GMapCatcher#472]
Hi, 

I am running into an issue with zoom levels when map tiles are exported from GMapCatcher. When I exported the maps, I specified min=-2 and max=2, then downloaded them in the OSM format.

The OSM tiles folder only shows zoom level 10, rather than various zoom levels. I saw that GMapCatcher does their zoom levels differently than other applications, but it seems like GMap converted their zoom levels to OSM zoom levels (since the folder has 10, and not -2, ... , 2). 

In GMapCatcher, -2 shows streets, neighborhoods, etc. and 2 shows a slightly zoomed out version. When i use these tiles in a personal application with Mapbox-gl js, they only show zoom level 10, which is similar to zoom level 2 in GMapCatcher. However, it does not display any streets on zoom in. It seems like it only downloaded those tiles at zoom level 2 and did not download the closer ones. 

I was wondering if this issue was known, or if I am not downloading them properly. Please let me know what you think. I can also post the folder if necessary; I did not think it was necessary to post my html code since it's a very simple app that just loads and displays a map.

Thanks

**Comment by heldersepu** [comment]
Can you provide a bit more details maybe pictures on your folder structure...
not sure what is that `OSM tiles folder` you mention

**Comment by heldersepu** [comment]
But if you can see the map in GMapCatcher like you mentioned:

> In GMapCatcher, -2 shows streets, neighborhoods, etc. and 2 shows a slightly zoomed out version. When i use these tiles in a personal application with Mapbox-gl js, they only show zoom level 10

Then the map tiles are there
 I guess your export/copy is not moving everything or your application is not reading the folder structure correctly

**Comment by evan0065** [comment]
Sure. OSM_tiles is the default folder that GMapCatcher creates on when the export map option is chosen for OSM tile type. I'll insert a screenshot of what it looks like through my file explorer then explain a bit. 

![image](https://user-images.githubusercontent.com/51757138/82232354-8643eb00-98fc-11ea-8370-22b6f4c86c6b.png)

![image](https://user-images.githubusercontent.com/51757138/82232309-7a582900-98fc-11ea-8a4c-8451bdf9b36d.png)

So the format for OSM files is {z}/{x}/{y}, where z = zoom level, x = x coord, y = y coord. The only zoom level is 10. Once that folder is entered, we see all the different x locations (image 1). Once we choose the x location, we see the tiles at different y locations (image 2). 

As per your last comment-- that's why I think that there's a problem with the export. I'm not sure what else could be causing the error

**Comment by heldersepu** [comment]
the export map option...
To be completely honest I completely forgot about that, this is what you are talking about:
https://github.com/heldersepu/GMapCatcher/blob/master/mapexport.py

I never tested that, and not sure anyone ever truly did, so ye, very likely has bugs

**Comment by evan0065** [comment]
Yeah, that's the one. And alright, I'll probably dig through that code and try to figure out what's happening

**Comment by evan0065** [comment]
Actually, that's a different one. I saw that it downloaded as a pdf, so that's probably the option when you right-click and choose 'export map', rather than options -> operations -> export map tiles. I will dig through the repo and find that file

**Comment by heldersepu** [comment]
Ohh I see, another feature with very little test:
https://github.com/heldersepu/GMapCatcher/blob/wiki/User_Guide.md#export-repo-tiles

if you show me what you are doing I can try to reproduce on my side, maybe I can spot the bug(s)

**Comment by evan0065** [comment]
Sure that would be great, thank you. 

Can't say that I'm doing much on my side though, but i'll walk through one of my runs. 
1. Open GMapCatcher (on windows, downloaded through exe file)
2. Zoom in to location (e.g. San Francisco (California))
3. Option button -> operation -> export map tiles
4. The center should already be set. I usually change area to be round numbers. 
   -> Change width to 200
   -> Change height to 100
5. Let's zoom in on the streets.
   -> Change min to -2
   -> Change max to 2
6. Under "Files", choose "OSM." Then choose folder location
7. Check "Overwrite existing ... " 
8. Export. (This one should be fast enough, it will take less than 5 minutes).

After this run, I see zoom levels 0-5 in the folder OSM_tiles. But it also does not download the SF region, it downloads the map as if it were on the smallest zoom level (I see every continent). 

For reference, looking at [mapbox zoom levels](https://docs.mapbox.com/help/glossary/zoom-level/), and [OSM Wiki on zoom levels](https://wiki.openstreetmap.org/wiki/Zoom_levels), the zoom levels should be on the larger side. I'm not aware of a specific conversion, so I do not know what specific zoom level it should be at. 

I'll keep on playing with the app and see if I can get something to work (or break). Let me know what you end up finding!

**Comment by heldersepu** [comment]
I just tested on my end and it seems to be working fine...
Now that export does not download anything, it just exports what you already have to a different format/location

**Comment by evan0065** [comment]
What do you mean, that export does not download anything, it just exports what you already have? So in order to export map tiles, do you need to download them first?

**Comment by heldersepu** [comment]
Here is what I've done, started with a clean slate no tiles in the directory

1. Download a small region 
2. Export a small subset of the region (all zoom levels)
3. Change directory to exported location
4. Verify only subset was exported and all zooms have tiles

All looks good, I can not see any issues

**Comment by evan0065** [comment]
Ah I see. I assumed that export downloaded the tiles for you instead of the other way around. Thank you for that clarification

**Comment by heldersepu** [comment]
If OSM format is just what you want change the default on the settings to that, so when they download they go on right format, no need to export unless you need to extract a smaller map subset
