### ISSUE TITLE
'Map' Screen is dark and mingy looking

### ISSUE THREAD

**Issue by Veek** [heldersepu/GMapCatcher#474]
[https://i.imgur.com/qPfufyu.png](https://i.imgur.com/qPfufyu.png)

It used to be brighter
[brighter](https://external-preview.redd.it/m-0qDY4LiY-xoH2pDYSCkoocgeC6tpBw9Wkpis16Jv4.png?auto=webp&s=60bcd4b64cbac3830b6e262a5b9acfd74cc9d631)

**Comment by heldersepu** [comment]
Bottom left of the GMapCatcher there is a toggle button that changes the darkness

**Comment by Veek** [comment]
thank you :)
