### ISSUE TITLE
gmapcatcher/mapServers/nokia.py uses here.com - JSON or REST + Oauth?

### ISSUE THREAD

**Issue by Veek** [heldersepu/GMapCatcher#475]
So my GMapCatcher started giving me _HTTP Error 401: Unauthorized_ because **HERE.com** expired the default key. 

1. So I signed in and created some new keys but it is not clear to me what I should use? **JSON or REST?** Also in REST should I use the OAuth token along with the app_id?

(works great with other map servers but I like Nokia to be working as well since I am used to it)
(I tried all combinations and none of it worked - I get the same error and in addition if I use JSON/REST **WITH NO OAuth** I suspect the **app_code** is too long.. I get a python traceback as well - but I can't replicate that currently)

2. How is the client authenticating with the servers - I couldn't find a setting for REST|JSON in the file - it just has a template URL?

3. How do I flush my tile cache and switch to "different folder per MapService"? Just rm -rf ./ and start over?

**Comment by heldersepu** [comment]
I think that the app_id is hardcoded here:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServers/nokia.py#L14-L15
