### ISSUE TITLE
No Zoom View for UK

### ISSUE THREAD

**Issue by Davierooker** [heldersepu/GMapCatcher#476]
I've tried various map providers, but all have extremely poor coverage of UK. Is this normal or is Gmapcatcher failing to download the tiles?

**Comment by heldersepu** [comment]
Can you be more specific...
When GMapCatcher fails to download or the tiles are not available you see:
https://github.com/heldersepu/GMapCatcher/blob/master/images/missing.png

The OpenStreetMap provider should cover the UK just fine
