### ISSUE TITLE
PHP and MySQL compatibility 

### ISSUE THREAD

**Issue by ronie19** [heldersepu/GMapCatcher#477]
I have vehicle GPS coordinates saved every 15 minutes to a MySQL table. Is there any way to fetch the coordinates and draw a path on the downloaded map ? 
One or more multiple vehicle paths ?
Show the same path on a php based browser ?

**Comment by heldersepu** [comment]
Yes to all ...
But that is not the purpose of GMapCatcher. 
You can create a PHP project that does what you need using many of the Maps API available, you don't really need GMapCatcher for that

**Comment by ronie19** [comment]
> Yes to all ...
> But that is not the purpose of GMapCatcher.
> You can create a PHP project that does what you need using many of the Maps API available, you don't really need GMapCatcher for that

Need offline map rather than online Google api. So need map downloaded on my hard disk for that purpose

**Comment by heldersepu** [comment]
> GPS coordinates saved every 15 minutes to a MySQL table ... multiple vehicle paths
How is that getting saved into the table? my guess is that some internet connection is required ...

But this customization I don't think adds any value to GMapCatcher ... 
if you are looking for a freelancer to code a project for you I suggest you try https://www.guru.com/d/freelancers/

**Comment by ronie19** [comment]
> > GPS coordinates saved every 15 minutes to a MySQL table ... multiple vehicle paths
> 
> How is that getting saved into the table? my guess is that some internet connection is required ...
> 
> But this customization I don't think adds any value to GMapCatcher ...
> if you are looking for a freelancer to code a project for you I suggest you try https://www.guru.com/d/freelancers/

SMS coordinates received by mobile network. Totally offline. A Linux system running on nginx webserver and MySQL database. I just want to display location or path from that saved data full-screen on a downloaded map.

**Comment by heldersepu** [comment]
Maybe instead of going down the php route...
you can use GMapCatcher markers:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapMark.py

Update the markers file with the coordinates of the vehicles as you get the data

**Comment by heldersepu** [comment]
![Screenshot from 2021-01-15 15-30-51](https://user-images.githubusercontent.com/545474/104775690-c5a23000-5746-11eb-8b26-0299353847ef.png)
