### ISSUE TITLE
ADD SOME NEW MARKER TO GMAP PLEASE

### ISSUE THREAD

**Issue by juangtju** [heldersepu/GMapCatcher#478]
Hello, I would like to know how to add different icons or images for the markers, since in the map I want to locate them by color,

**Comment by juangtju** [comment]
Please i really need that for a company when i working on

**Comment by heldersepu** [comment]
Look in:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapMark.py

**Comment by heldersepu** [comment]
The default marker is: 
https://github.com/heldersepu/GMapCatcher/blob/master/images/marker.png

**Comment by juangtju** [comment]
me again, Inglés

what I need is to be able to put several colored markers a total of ten on the map, as well as the default red, not just change what comes from the factory. but I don't know much about python, please help me with this, I will be grateful

**Comment by juangtju** [comment]
It is to separately identify several people, in this case sellers of a small company and thus score where they have sold on the map

**Comment by juangtju** [comment]
> 
> 
> The default marker is:
> https://github.com/heldersepu/GMapCatcher/blob/master/images/marker.png
> https://github.com/heldersepu/GMapCatcher/blob/master/images/marker_s.png

give me some hints on how to start the code please.

**Comment by heldersepu** [comment]
If you don't know Python this will be quite a complex task for you...
One idea is to add more marker images then change the markers file (read and write) to include the specific image per marker

**Comment by juangtju** [comment]
ok thanks for the advice, but I need to have that function, I don't know the language but I learn quickly, I don't need contextual menus to change the marker, it could just be to assign a letter on the keyboard so that according to the position of the mouse press said letter and me put a different bookmark, and save it in the bookmarks list, just make it another icon

**Comment by juangtju** [comment]
(bookmark) is refeer to "marker"

**Comment by heldersepu** [comment]
Start reading the code on the mapMark.py and ask if you have any specific programming questions

**Comment by juangtju** [comment]
ok thanks , i take a look for it

**Comment by heldersepu** [comment]
Look at my history I did some work on markers that I never merged into the master branch:
https://github.com/heldersepu/GMapCatcher/commit/4310f60d026766d0a53df08ff6126c65dc299b07
https://github.com/heldersepu/GMapCatcher/commit/83efa1cbbab91d9fd197e347f302c90eb45048e9
Let's see if I can merge all that without conflicts

**Comment by heldersepu** [comment]
Shift + Right-click on the map now brings up a new window
![image](https://user-images.githubusercontent.com/545474/104945106-38e5b500-5986-11eb-9c09-e977bd87c48b.png)

And the markers file will have an additional option (image=)
![Screenshot from 2021-01-18 12-14-47](https://user-images.githubusercontent.com/545474/104945477-cd501780-5986-11eb-9883-01af46dec19d.png)

**Comment by juangtju** [comment]
wonderful , that is i really need , I'm currently seeing how I add the code to the map catcher, thanks

**Comment by heldersepu** [comment]
The code has been added...
Those screenshot I posted,  that feature is now on the master branch

**Comment by juangtju** [comment]
ok thanks , but one think, when I put the markers from far away they can be seen but from near they can't be seen because it will be ???

**Comment by heldersepu** [comment]
look at the zoom value in the markers file, that control if they are seen near or far
