### ISSUE TITLE
Problems with GMapCatcher

### ISSUE THREAD

**Issue by Gaboes** [heldersepu/GMapCatcher#479]
Hi ! some months ago, i have some problems because gmapcatcher show me this message " We don't have maps 
for this zoom level or region " i have tried a lot of  map service but nothing, some one has the same problem?

**Comment by MrD-RC** [comment]
I first noticed this yesterday, and is still happening now. About a week ago I had no issues at all. But now, cannot download complete tiles.

**Comment by heldersepu** [comment]
What map service are you using?

**Comment by heldersepu** [comment]
To troubleshoot look in the code for the map service you are using

https://github.com/heldersepu/GMapCatcher/tree/master/gmapcatcher/mapServers

And see if the tiles load in your browser,  for example 
https://a.tile.openstreetmap.org/1/1/1.png
That looks fine for me

**Comment by MrD-RC** [comment]
No, there is definitely a problem. It is the same on every map provider I have tried in the settings, and have had the same issue reported by a lot of other people, in different countries. This is what you get:

![image](https://user-images.githubusercontent.com/17590174/107148474-26d6b100-694b-11eb-913d-994462d4fc4b.png)

* Changing the map service doesn't make a difference
* Selecting Force Download doesn't make a difference
* Changing between Map, Satellite, and Terrain doesn't make a difference

This was all working fine about a week ago.

**Comment by ArdSchell** [comment]
Change Theme -> Map Service -> Select your favorite map service: Virtual Earth

**Comment by heldersepu** [comment]
Sorry, works fine for me:
http://a3.ortho.tiles.virtualearth.net/tiles/a1201223.png?g=392
http://a0.ortho.tiles.virtualearth.net/tiles/a1201222.png?g=392

**Comment by heldersepu** [comment]
But yes it is possible that VirtualEarth is blocking excessive use of GMapCatcher, it's not the first time that map server does that...
I strongly recommend you to use OpenStreetMap instead

**Comment by leeph** [comment]
I've tried every combination of Map Providers and offline / force update / map type. I just get blank tiles everywhere. I get the occasional few tiles at very wide zoom levels (14 and above) but absolutely nothing at any usable zoom level.

Program is broken, I'm sorry to say. I would urge the maintainers to actually check for themselves rather than assuming we're all having some sort of isolated issue.

**Comment by heldersepu** [comment]
I did check here is a screenshot from freshly downloaded tiles from Oslo on a windows machine
![image](https://user-images.githubusercontent.com/545474/107155004-f3445880-6943-11eb-97a2-703ac6e04bbc.png)

**Comment by heldersepu** [comment]
Here is another from Oulu on a different computer this time Ubuntu Linux
![Screenshot from 2021-02-07 12-59-42](https://user-images.githubusercontent.com/545474/107155088-749beb00-6944-11eb-9f41-494376052c69.png)

**Comment by leeph** [comment]
I am starting to suspect some sort of regional or national issue then. Is there anything in your code that relies upon connections succeeding to some place regardless of map provider?

Some host somewhere that might be filtering connections from outside your country or something?

I raised this with my friend Darren Lines who commented above - it was working for him last week and now it isn't, and it's not working for me either.

As the author of the code you are best placed to diagnose this issue but I assure you there is an issue regardless of whether it works in your limited testing.

Thanks for looking into it, though.

**Comment by heldersepu** [comment]
Sorry @leeph as you can see on those screenshots it works fine for me...

and those comments are not helping your cause:
> I would urge the maintainers to actually check for themselves rather than assuming ...

Yes I'm the sole maintainer/owner of this project, and you are the one assuming I did not test.
GMapCatcher OpenSource and distributed free, but my time is not. 
I can't troubleshoot this for you, if you can't read Python code hire someone to do it for you!

**Comment by leeph** [comment]
Wow okay... maybe you didn't read my follow up comment?

I don't have time to debug your code. I guess I will just have to find another program to do this because your program is broken for a lot of people, but it's okay because it works for you, right? ;)

Ciao.

**Comment by heldersepu** [comment]
Yes @leeph, you don't have time to debug the code, or to write code, your time must be more valuable than contribute back to other opensource projects. That is why your profile is empty:
https://github.com/leeph?tab=repositories

Yes please go find another program, I honestly created this just for myself and the "NO WARRANTY" in the license is a reflection of that:
https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html

**Comment by heldersepu** [comment]
New release published:
https://github.com/heldersepu/GMapCatcher/releases

That fixes an issue with Nokia maps, but VirtualEarth has been working fine.
see Issue https://github.com/heldersepu/GMapCatcher/issues/481 for more details
Hopefully that fixes your issue(s)

_____


My guess you did not really change the server ... 
>It is the same on every map provider
>tried every combination of Map Providers

When I see those broad statements I go and test with my favorite (OpenStreetMap) if it works then statements are wrong, users did not really try every provider.

You probably thought you did but the change provider but change did not take effect.
After changing map server click save then close and open GMapCatcher and go back into settings to make sure the correct map server is in place
