### ISSUE TITLE
Gmap catcher

### ISSUE THREAD

**Issue by Eg681** [heldersepu/GMapCatcher#480]
I've been trying to get the satellite and terran view working on this but no joy, even the standard view won't work below zoom level 7, I see others are having same problem. Please advise on this issue. Thanks

**Comment by heldersepu** [comment]
Can you provide more details on what exactly have you tried?
As far as I can see it all works fine: https://github.com/heldersepu/GMapCatcher/issues/479

**Comment by Eg681** [comment]
Yes and thanks for quick response, I've downloaded GmapCatcher twice trying
to get it working. I'm using windows 7 and downloading from github it opens
up fine and will show map if standard is selected top choice says map, if I
choose satellite view or terran it goes away showing black tiles even if
standard selected can not zoom below 7 or 8 without getting page of black
tiles. I've been in settings trying each map server but same results, I've
also tried 2 different pc one with windows 7 the other windows 8, I've
watched many YouTube videos and people simply choose map,satellite or
terran view but not for me. Any help will be appreciated.

**Comment by heldersepu** [comment]
Same as others reported I have no clue what you are experiencing... 

On the map servers stick to OpenStreetMaps, that is the easiest to troubleshoot, you need to inspect the network traffic see what is going on with the tile downloads, also the installer has a command line downloader (download.exe) you can try that see if there is any additional output on the console


Will be best if you could troubleshoot on debug mode, try to follow the instructions here:
https://github.com/heldersepu/GMapCatcher/blob/wiki/devEnv.md

**Comment by Eg681** [comment]
Ok thanks I'll try what you suggested, there's simply no satellite or
terran view which is need to fly because of the map detail. Is it possible
there's problem with my laptop's settings? I'm just guessing.  Thanks
again for your help

**Comment by heldersepu** [comment]
For troubleshooting purposes stay away from satellite or terrain views, stick to OpenStreetMaps where the only option is maps.

You mentioned:
>I've been in settings trying each map server but same results

Have you tried OpenStreetMaps?   
We have to truly isolate this issue, if no map server works it's very different than just one or two servers blocking you

**Comment by Eg681** [comment]
Yes I have tried open street maps but no change when I do, only thing I
just noticed if zoom level around 15 16 the satellite and terran view is
working, if I slide up any further on zoom slider map goes away and page
fills with black tiles. Maybe this is clue as far as troubleshooting.

**Comment by heldersepu** [comment]
There are no satellite or terrain view in OpenStreetMaps, that is not even an option

![Screenshot from 2021-02-07 16-43-04](https://user-images.githubusercontent.com/545474/107160361-c607a280-6963-11eb-9f8c-562796f45ed7.png)

Are you sure you tried OpenStreetMaps?

**Comment by Eg681** [comment]
If it's in settings I tried each one at a time, I'll get pc booted back up
and try again and let you know. Thanks for help

**Comment by heldersepu** [comment]
here is a sample command for you to test:
`download.exe --latitude=37 --longitude=23`

![image](https://user-images.githubusercontent.com/545474/107161932-f6ecd500-696d-11eb-9cc0-aaa04ead8101.png)


let's see if you see any errors that way

**Comment by Eg681** [comment]
Please explain how I run this exercise, do I use the gmapcatcher it self or
what I'm not sure?

**Comment by heldersepu** [comment]
The screenshot should be all the explanation you need...
Have you even used the command line (cmd) to troubleshoot?

**Comment by heldersepu** [comment]
Sorry but I really don't have time for this, see if you can reach out to a developer local to you for further assistance

**Comment by Eg681** [comment]
I'm in southern wv and don't think there's any local help, I've been in
touch with some Youtubers maybe we can figure this out.

**Comment by heldersepu** [comment]
New release published:
https://github.com/heldersepu/GMapCatcher/releases

That fixes an issue with Nokia maps, all other maps should have been working fine.
see Issue https://github.com/heldersepu/GMapCatcher/issues/481 for more details
Hopefully that fixes your issue(s)

_____


My guess you did not really change the server ... 
>been in settings trying each map server but same results

You probably thought you did but the change did not take effect,
After changing did you close and open GMapCatcher to make sure the correct map server was in place?

**Comment by Eg681** [comment]
Thanks for getting back to me, I'm still fighting this but your right when
I change map server I hit save but don't reboot and did notice when I go
back into settings the change was not saved so I'll try changing map server
then reboot and see if it has actually changed, I let you know if it works.
Thanks again

**Comment by heldersepu** [comment]
Also don't forget to upgrade to latest ...
that should fix the issue with Nokia

**Comment by Eg681** [comment]
Will do, thanks!

**Comment by Eg681** [comment]
Will by checking force update do the trick or will I need to reinstall?

**Comment by heldersepu** [comment]
The force update check box only applies to map tiles...

To upgrade you need to download latest installer (GMapCatcher-0.8.2.1.exe) from:
https://github.com/heldersepu/GMapCatcher/releases
Then install it as you normally do any other application

**Comment by Eg681** [comment]
Ok thanks will do

**Comment by heldersepu** [comment]
If you have time go over the user guide:
https://github.com/heldersepu/GMapCatcher/blob/wiki/User_Guide.md
It could use a refresh with instructions for new users

**Comment by Eg681** [comment]
I followed your instructions and it works great pretty much any map I
choose, good job and Thanks you

**Comment by Eg681** [comment]
I will go over the guide, nice app. Thanks again

**Comment by Eg681** [comment]
One last question and I'll get out of your way, I did go over user guide
but alittle confused, can I download map in zoom level 5 2 1 or do I have
to download 5 4 3 to make it work on radio 3 way switch?

**Comment by heldersepu** [comment]
Not sure I understand your question, so here is my best...

You can download what ever you want, ye skip zoom levels or just delete them after on the file system by default they are just a folder.
Use the download for the levels you want on the UI:
https://github.com/heldersepu/GMapCatcher/blob/wiki/User_Guide.md#download
or get familiar with the command line download and create a batch script to automate your downloads

but the "make it work on radio" I guess you are assuming I know what you use GMapCatcher for, I do not have any clue!

**Comment by Eg681** [comment]
Ok thanks for help
