### ISSUE TITLE
I can't download my tiles 

### ISSUE THREAD

**Issue by Moksh-2000** [heldersepu/GMapCatcher#481]
Hello sir , recently I download new tiles for jumper t16 radio but I can't download any tiles even any other place , there is only 15 and 16 folders are there 

What can I do ?

![IMG_20210208_073808](https://user-images.githubusercontent.com/58510260/107170129-99946a80-69e5-11eb-8198-eab60d7b2159.jpg)

**Comment by Moksh-2000** [comment]
Yeah it's working , I'm sorry about it

![Uploading IMG_20210208_081731.jpg…]()

My map provider are "Nokia" 😂🤣😂🤣

https://github.com/heldersepu/GMapCatcher/issues/479#issuecomment-774685640
It's really help me 😛

**Comment by heldersepu** [comment]
Can you clarify what exactly was the issue?
You had Nokia and now switched to VirtualEarth and all works??

**Comment by Moksh-2000** [comment]
Yeah it's perfect work on VirtualEarth not on Nokia 😁

**Comment by heldersepu** [comment]
I see an issue on the Nokia servers they changed a few things... will fix it and send a new release

**Comment by heldersepu** [comment]
New release published: 
https://github.com/heldersepu/GMapCatcher/releases

**Comment by heldersepu** [comment]
If you have time go over the user guide:
https://github.com/heldersepu/GMapCatcher/blob/wiki/User_Guide.md
It could use a refresh with instructions for new users

**Comment by Moksh-2000** [comment]
Ok i will update and tell you
