### ISSUE TITLE
OpenStreetMap does not work

### ISSUE THREAD

**Issue by AdClear247** [heldersepu/GMapCatcher#482]
It no longer works at any zoom level. I tried using proxy too. Previously it worked. It makes some connections, but did not observe network headers.

**Comment by heldersepu** [comment]
I just tested ... seems to be working fine

**Comment by AdClear247** [comment]
Weird. Yandex does not work either. I will try different proxy and vpn, maybe it is my odd network configuration.

**Comment by AdClear247** [comment]
It does not work because says 403 - Forbidden. Observed via Fiddler. However when I open same URL via Firefox, it works. However when I change user agent in Firefox to the same one as in GMapCatcher, it also says Forbidden. So looks like user agent is blocked of your app. Can't understand why this works for you. Looks like not IP ban.
![Untitled](https://user-images.githubusercontent.com/81487643/112739323-cb509900-8f73-11eb-885d-c3ce5a5a78eb.jpg)
![Untitled2](https://user-images.githubusercontent.com/81487643/112739330-d7d4f180-8f73-11eb-994e-526557b7d8e0.jpg)

**Comment by heldersepu** [comment]
Yes you are right, I most have changed the agent on my config a while ago...
Look for `.GMapCatcher/gmapcatcher.conf` that is under your user profile there are settings for agent there

**Comment by AdClear247** [comment]
Even when I changed User Agent to my Browser's one it now says HTTP 418 - Blocked in Fiddler. Even if I directly change user agent via Fiddler's options menu. So looks like this is something more than user agent problem, maybe other headers like accept-encoding...
