### ISSUE TITLE
Is there a way to add data pulled from Google, to a map in GMapCatcher using python

### ISSUE THREAD

**Issue by Veek** [heldersepu/GMapCatcher#483]
So with the '**_Virtual Earth_**' map option I get a lot of clear road data (visual data) - the trouble is, some of this data is utterly wrong so were I to actually use this data by counting roads I would be utterly lost very soon. 

What I need is some location data taken from Google and merged with **_VirtualEarth_** that way even if I lose my way in a new place, I could move to the nearest Police Station or landmark and then continue on my way and continue to use the map/GMapCatcher. It also allows me to crosscheck that I am on the correct street.

How do I do this?  (Google provides post office, police station and park data that I would like to insert with Marker pins into GMapCatcher) Then should I lose my way I can ask someone for directions to my nearest marker.

Currently 
1. I print out maps using Virtual Earth onto A4 sheet (I can clean them up a little using GIMP - darken it for clear lettering)
2. I setup interesting markers in GMapCatcher using Google Map Maker
3. Then I toggle between Google Map Maker and Virtual Earth and painfully locate the places on the A4 and by constantly toggling, write out the data manually onto the A4.

**Comment by heldersepu** [comment]
No, sorry that is not what GMapCatcher is intended for ...
I get a feeling that you should be using OpenStreetMap (OSM), with OSM you can edit the maps:
https://www.openstreetmap.org/ you can add any missing roads or make edits on anything wrong.

There are many features/markers you can add to OSM to identify landmarks:
https://wiki.openstreetmap.org/wiki/Map_features

Start here:
https://wiki.openstreetmap.org/wiki/Beginners%27_guide

And once you submit your corrections/addition those maps can be downloaded for offline use with GMapCatcher
