### ISSUE TITLE
Fix or remove OpenStreetMap

### ISSUE THREAD

**Issue by MinuteAd8502** [heldersepu/GMapCatcher#484]
I previously reported this, but you have done nothing.
Figured out way how to fix it, via HTTP Debugger I changed one header and added one header.
Changed User-Agent header to `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0`
Added Accept-Language header `en-US,en;q=0.5`.
Now it works, no more HTTP responses 403 forbidden or some "blocked" (when change ua but not add accept-language).
Of course we can remove OSM server ourselves via choose servers option, did not know that before.

**Comment by heldersepu** [comment]
if they are blocking the User-Agent we should not circumvent , just use a different provider

**Comment by MinuteAd8502** [comment]
Looks like they do intentionally. But still my fav is OSM. Even they mention in their wiki that downloading tiles is possible using many apps, but for some reason not mentioning your app. Luckily they offer many more apps suggestions both for detailed real maps and navigation for all systems, some of which may be more efficient than images only.
