### ISSUE TITLE
Google Satellite does not work

### ISSUE THREAD

**Issue by MinuteAd8502** [heldersepu/GMapCatcher#485]
I know you disabled Google by default so I enabled it via choose servers option.
Google works, but Google satellite not. Regardless of zoom level. HTTP message observed via HTTP Debugger is 404 Not Found.

**Comment by heldersepu** [comment]
read https://github.com/heldersepu/GMapCatcher/issues/210

**Comment by MinuteAd8502** [comment]
I knew that is probably reason why you turned off that server by default. But why would only Google and Google Terrain and Google Hybrid work, but Google Satellite not. Maybe something has to be modified or updated to fix it? Or remove Google altogether.
