### ISSUE TITLE
can't view specific place on map

### ISSUE THREAD

**Issue by AcrobaticFlamingo53** [heldersepu/GMapCatcher#492]
Whenever I access this specific place, there are white rectangles, and even if I force update, online mode, it does not download anything, and after exiting app says see log. I am using sqlite3 db format. Can I somehow fix db to be able to re download damaged tiles? I think error started appearing after sudden power loss or download interruption. Error only appears when I see these specific white tiles. If I don't see them, then app exits without mentioning any error log. Here is log:
```
Traceback (most recent call last):
  File "maps.py", line 851, in expose_cb
  File "gmapcatcher\mapDownloader.pyc", line 179, in query_region_around_point
  File "gmapcatcher\mapDownloader.pyc", line 167, in query_region
  File "gmapcatcher\mapDownloader.pyc", line 142, in query_tile
  File "gmapcatcher\gtkThread.pyc", line 41, in cb
  File "maps.py", line 914, in tile_received
TypeError: Gdk.Drawable.draw_pixbuf() argument 2 must be gtk.gdk.Pixbuf, not None
```

**Comment by AcrobaticFlamingo53** [comment]
I found exactly which tile and it looks like unfinished png file in DB Browser for sqlite. Only deleting it via that app fixes issue.
But difficult to find and slow. Hmmm...maybe if I use some other db format it won't have problems with incomplete files. Will maybe try to export or something.
![Untitled](https://user-images.githubusercontent.com/90701210/135757069-dc78372d-dae0-4869-b5de-d453ea3b3098.jpg)

**Comment by heldersepu** [comment]
The sqlite3 db format was not the most tested format, you should try a different format or delete the db file and download again...
Also to reproduce this issue someone will need know more about this "specific place on map" and what map provider

**Comment by AcrobaticFlamingo53** [comment]
Well, I recreated issue by renaming old file and making new, and interrupting connection before few tiles download.
Same issue. It's Nokia Maps satellite, but it's same issue with any place and any map. Maybe you could add some way so that incomplete files don't get saved or that they can be detected, fixed, removed. In the meantime I will try files method instead of sqlite3.

**Comment by AcrobaticFlamingo53** [comment]
OK, I tried. When I interrupted connections using Proxifier (difficult to do with fast internet, have to use some app like NetLimiter to throttle connection to old modem speeds like 8 kB/s) white damaged tiles appeared. But they immediately quickly fix themselves, in just one case had to zoom out than in to fix it. So I will then use the default **files** method from now on.

**Comment by heldersepu** [comment]
Happy to hear you got a workaround...
I personally was never a big fan of the sqlite format... i might have use it a few times when we introduce it.

  I think it will be best to disable that option in the selection

**Comment by heldersepu** [comment]
Just from a quick look at the code this should be working:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/tilesRepo/tilesRepoSQLite3.py#L403

Someone  will have to debug that function see why the tile is not getting deleted on the DB
