### ISSUE TITLE
Skyvector Update

### ISSUE THREAD

**Issue by darknessbxy** [heldersepu/GMapCatcher#494]
Before:    return 'http://t%i.skyvector.net/tiles/301/1211/%i/%i/%i.jpg'

After:       return 'https://t.skyvector.com/V7pMh4zRihflnr61/304/2213/%i/%i/%i.jpg'

Does anyone know how to update the .pyc files?

**Comment by heldersepu** [comment]
Can you add some more details
What is the problem?

**Comment by darknessbxy** [comment]
How can I update the Skyvector map?
I wanted to edit the code of the files but they are already compiled.
Or if there will be any way to download the Skyvector map.
I found in the code that is outdated the URL where the images are.

An example of a current link is `https://t.skyvector.com/V7pMh4zRihflnr61/304/2213/18/0/0.jpg`

**Comment by heldersepu** [comment]
the code is here:
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServers/WorldHI.py
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServers/WorldLO.py
https://github.com/heldersepu/GMapCatcher/blob/master/gmapcatcher/mapServers/WorldVFR.py

I get a feeling you are new to python, and have not set your environment to be compile the code, this might be useful:
https://github.com/heldersepu/GMapCatcher/blob/wiki/devEnv.md
