### ISSUE TITLE
Usage in Ubuntu 22.04

### ISSUE THREAD

**Issue by arattlesnake** [heldersepu/GMapCatcher#496]
Thanks for supporting gmapcatcher. Massively useful program. My team has been using it heaps in Windows.

However, I'm wanting to use it in Ubuntu 22.04 but there doesn't appear to be anyway to run it once its downloaded. The readme doesn't give sufficient instruction or the location of any type of executable to open a gui. Is the readme able to be updated to include instructions for use on Linux/Ubuntu, please?

**Comment by heldersepu** [comment]
gmapcatcher was built using Python 2.x   ... Ubuntu 22.04 no longer supports that version 

see https://github.com/heldersepu/GMapCatcher/issues/469
