### ISSUE TITLE
Run GMapCatcher

### ISSUE THREAD

**Issue by farfaraway2121** [heldersepu/GMapCatcher#497]
Hi, I dont know what command to use to run gmapcatcher in linux mint 21.
The user manual does not say what command to use to start or run gmapcatcher and gmapcatcher does not appear in the list of installed software.
 I ran this command:  $ git clone https://github.com/heldersepu/gmapcatcher
on linux mint 21 and it seemed to download and install a lot of files and I think I already installed python a while ago. 
gmapcatcher  does appear in a folder on the hard drive in  /home/explorer/gmapcatcher/gmapcatcher
Please, what command to run the program gmapcatcher? 
Thanks

**Comment by heldersepu** [comment]
You should be able to do `python maps.py`
